Update Makefile.test

diff --git a/Makefile.test b/Makefile.test
--- a/Makefile.test
+++ b/Makefile.test
@@ -68,22 +68,22 @@ all_pdf: $(patsubst $(test_dir)/%.input,$(test_dir)/%.pdf,$(input_files))
 
 %.dot: %.xml $(xsl)
 	# Check the existence of xsltproc
-	ifdef XSLTPROC 
-		@echo "xsltproc is installed."
-	else 
-    		@echo "Error: xsltproc is not installed."
-		@exit 1
-	endif
+	if XSLTPROC then \ 
+		@echo "xsltproc is installed.";\
+	else \
+    	@echo "Error: xsltproc is not installed."; \
+		@exit 1; \
+	fi
 	@$(XSLTPROC) $(xslfile) $*.xml > $@
 
 %.pdf: %.dot
 	# Check the existence of dot (Graphviz)
-	ifdef DOT
-		@echo "dot (Graphviz) is installed."
-	else
-		@echo "Error: dot (Graphviz) is not installed."
-		@exit 1
-	endif
+	if DOT then \
+		@echo "dot (Graphviz) is installed."; \
+	else \
+		@echo "Error: dot (Graphviz) is not installed."; \
+		@exit 1; \
+	fi
 	@$(DOT) -T pdf -o $@ $<
 
 %.fsa: %.tmp-morpho %.tmp-pattern
